import { useEffect, useMemo, useState } from "react";
import type { JamOsRuntimeV2, FileEntry } from "../../runtime/types";
import { basename, normalizePath, parentPath } from "../../protocols/jamFs";

export function Files({ runtime, serviceId, openApp }: { runtime: JamOsRuntimeV2; serviceId: string | null; openApp: (id: string, args?: string) => void }) {
  const [path, setPath] = useState("/home/user"); const [nodes, setNodes] = useState<FileEntry[]>([]); const [error, setError] = useState(""); const [status, setStatus] = useState(""); const fs = useMemo(() => serviceId ? runtime.fs.mount(serviceId) : null, [runtime, serviceId]);
  const refresh = async () => { if (!fs) return; try { setNodes(await fs.list(path)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to list directory"); } };
  useEffect(() => { void refresh(); }, [path, fs]);
  const createFolder = async () => { const name = window.prompt("Folder name", "new-folder"); if (!name || !fs) return; setStatus("Saving…"); try { await fs.mkdir(normalizePath(`${path}/${name}`)); setStatus("Saved"); await refresh(); } catch (cause) { setStatus("Save failed"); setError(cause instanceof Error ? cause.message : "Unable to create folder"); } };
  const createFile = async () => { const name = window.prompt("File name", "notes.txt"); if (!name || !fs) return; setStatus("Saving…"); try { await fs.writeText(normalizePath(`${path}/${name}`), ""); setStatus("Saved"); await refresh(); } catch (cause) { setStatus("Save failed"); setError(cause instanceof Error ? cause.message : "Unable to create file"); } };
  const remove = async (node: FileEntry) => { if (!fs || !window.confirm(`Delete ${basename(node.path)}?`)) return; setStatus("Saving…"); try { await fs.remove(node.path, { recursive: node.type === "directory" }); setStatus("Saved"); await refresh(); } catch (cause) { setStatus("Save failed"); setError(cause instanceof Error ? cause.message : "Unable to remove item"); } };
  if (!fs) return <div className="empty-state"><h2>Storage is not mounted</h2><p>Start the Computer Service to access JAM FS.</p></div>;
  return <div className="file-app"><div className="file-toolbar"><button onClick={() => setPath(parentPath(path))}>←</button><input value={path} onChange={(event) => setPath(event.target.value)} onKeyDown={(event) => event.key === "Enter" && setPath(normalizePath(event.currentTarget.value))} /><button onClick={() => void refresh()}>↻</button><button onClick={createFolder}>New folder</button><button onClick={createFile}>New file</button></div><div className="file-places"><button onClick={() => setPath("/home/user")}>Home</button><button onClick={() => setPath("/home/user/Desktop")}>Desktop</button><button onClick={() => setPath("/home/user/Documents")}>Documents</button><button onClick={() => setPath("/home/user/Projects")}>Programs</button><button onClick={() => setPath("/home/user/Sites")}>Services</button></div><div className="file-list">{path !== "/" && <button className="file-row" onDoubleClick={() => setPath(parentPath(path))}><span>↩</span><span>..</span><small>parent</small></button>}{nodes.map((node) => <div className="file-row" key={node.path} onDoubleClick={() => node.type === "directory" ? setPath(node.path) : openApp("playground", node.path)}><span>{node.type === "directory" ? "📁" : "📄"}</span><strong>{basename(node.path)}</strong><small>{node.type === "directory" ? "Directory" : `${node.size} bytes`}</small><button onClick={(event) => { event.stopPropagation(); void remove(node); }}>Delete</button></div>)}</div>{error && <p className="error-text">{error}</p>}{status && <p className={status === "Save failed" ? "error-text" : "success-text"}>{status}</p>}<div className="file-footer">JAM FS · {path}</div></div>;
}
