import { Code2, FilePlus2, FolderPlus, House, Monitor, RefreshCw, Server, Undo2 } from "lucide-react";
import { FileText, FolderSimple } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import type { JamOsRuntimeV2, FileEntry } from "../../runtime/types";
import { basename, normalizePath, parentPath } from "../../protocols/jamFs";

export function Files({ runtime, serviceId, openApp }: { runtime: JamOsRuntimeV2; serviceId: string | null; openApp: (id: string, args?: string) => void }) {
  const [path, setPath] = useState("/home/user");
  const [nodes, setNodes] = useState<FileEntry[]>([]);
  const [error, setError] = useState("");
  const [status, setStatus] = useState("");
  const fs = useMemo(() => serviceId ? runtime.fs.mount(serviceId) : null, [runtime, serviceId]);
  const refresh = async () => { if (!fs) return; try { setNodes(await fs.list(path)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to list directory"); } };
  useEffect(() => { void refresh(); }, [path, fs]);
  const createFolder = async () => { const name = window.prompt("Folder name", "new-folder"); if (!name || !fs) return; setStatus("Saving…"); try { await fs.mkdir(normalizePath(`${path}/${name}`)); setStatus("Saved"); await refresh(); } catch (cause) { setStatus("Save failed"); setError(cause instanceof Error ? cause.message : "Unable to create folder"); } };
  const createFile = async () => { const name = window.prompt("File name", "notes.txt"); if (!name || !fs) return; setStatus("Saving…"); try { await fs.writeText(normalizePath(`${path}/${name}`), ""); setStatus("Saved"); await refresh(); } catch (cause) { setStatus("Save failed"); setError(cause instanceof Error ? cause.message : "Unable to create file"); } };
  const remove = async (node: FileEntry) => { if (!fs || !window.confirm(`Delete ${basename(node.path)}?`)) return; setStatus("Saving…"); try { await fs.remove(node.path, { recursive: node.type === "directory" }); setStatus("Saved"); await refresh(); } catch (cause) { setStatus("Save failed"); setError(cause instanceof Error ? cause.message : "Unable to remove item"); } };
  if (!fs) return <div className="empty-state"><h2>Storage is not mounted</h2><p>Start the Computer Service to access JAM FS.</p></div>;
  return <div className="file-app"><div className="file-toolbar"><button onClick={() => setPath(parentPath(path))} aria-label="Go to parent folder" title="Go to parent folder"><Undo2 size={16} /></button><div className="file-path-field"><House size={14} /><input value={path} onChange={(event) => setPath(event.target.value)} onKeyDown={(event) => event.key === "Enter" && setPath(normalizePath(event.currentTarget.value))} aria-label="Current path" /></div><button onClick={() => void refresh()} aria-label="Refresh folder" title="Refresh"><RefreshCw size={15} /></button><button onClick={createFolder}><FolderPlus size={15} /> <span>New folder</span></button><button onClick={createFile}><FilePlus2 size={15} /> <span>New file</span></button></div><div className="file-places"><button onClick={() => setPath("/home/user")}><House size={15} />Home</button><button onClick={() => setPath("/home/user/Desktop")}><Monitor size={15} />Desktop</button><button onClick={() => setPath("/home/user/Documents")}><FileText size={16} weight="duotone" />Documents</button><button onClick={() => setPath("/home/user/Projects")}><Code2 size={15} />Projects</button><button onClick={() => setPath("/home/user/Sites")}><Server size={15} />Services</button></div><div className="file-list">{path !== "/" && <button className="file-row parent-row" onDoubleClick={() => setPath(parentPath(path))}><span className="file-row-icon"><Undo2 size={18} /></span><span>..</span><small>Parent folder</small></button>}{nodes.map((node) => <div className="file-row" key={node.path} onDoubleClick={() => node.type === "directory" ? setPath(node.path) : openApp("playground", node.path)}><span className="file-row-icon">{node.type === "directory" ? <FolderSimple size={24} weight="duotone" /> : <FileText size={23} weight="duotone" />}</span><strong>{basename(node.path)}</strong><small>{node.type === "directory" ? "Folder" : `${node.size} bytes`}</small><button onClick={(event) => { event.stopPropagation(); void remove(node); }}>Delete</button></div>)}</div>{error && <p className="error-text">{error}</p>}{status && <p className={status === "Save failed" ? "error-text" : "success-text"}>{status}</p>}<div className="file-footer">JAM FS <span>·</span> {path}</div></div>;
}
