import type { JamFileSystem } from "../../jam/filesystem";
import type { JamNameService } from "../../jam/names";
import DOMPurify from "dompurify";
import { canonicalizeUrl, parseJamUri, schemeOf, type BrowserScheme } from "../../protocols/jamUri";
import { normalizePath } from "../../protocols/jamFs";

export interface BrowserResolvedDocument { canonicalUrl: string; scheme: BrowserScheme; title?: string; mode: "remote-frame" | "srcdoc" | "internal"; frameUrl?: string; srcdoc?: string; jam?: { serviceId?: string; name?: string; path?: string }; }
export interface BrowserResolutionContext { localFs: JamFileSystem | null; names: JamNameService; siteForService: (serviceId: string) => Pick<JamFileSystem, "readPublished" | "manifest">; }
export async function resolveBrowserUrl(rawUrl: string, context: BrowserResolutionContext): Promise<BrowserResolvedDocument> {
  const canonicalUrl = canonicalizeUrl(rawUrl); const scheme = schemeOf(canonicalUrl);
  if (scheme === "http" || scheme === "https") return { canonicalUrl, scheme, mode: "remote-frame", frameUrl: canonicalUrl, title: new URL(canonicalUrl).hostname };
  if (scheme === "about") return { canonicalUrl, scheme, mode: "internal", srcdoc: `<main class="browser-internal"><h1>JAM Browser</h1><p>${canonicalUrl === "about:blank" ? "Enter a JAM name, file path, or Web address." : canonicalUrl}</p></main>` };
  if (scheme === "file") { const fs = context.localFs; if (!fs) throw new Error("Connect or create a Computer Service before opening JAM FS content"); const url = new URL(canonicalUrl); const path = normalizePath(decodeURIComponent(url.pathname)); const stat = await fs.stat(path); if (stat.type === "directory") { const children = await fs.list(path); return { canonicalUrl, scheme, mode: "srcdoc", title: path, srcdoc: `<main class="directory-index"><h1>${path}</h1><ul>${children.map((n) => `<li>${n.type === "directory" ? "📁" : "📄"} ${escapeHtml(n.path.split("/").pop() || "")}</li>`).join("")}</ul></main>`, jam: { path } }; } const content = await fs.read(path); return { canonicalUrl, scheme, mode: "srcdoc", title: path.split("/").pop(), srcdoc: renderFile(content, path, false), jam: { path } }; }
  const parsed = parseJamUri(canonicalUrl); const record = parsed.serviceId ? { serviceId: parsed.serviceId } : await context.names.resolve(parsed.name!); const targetFs = context.siteForService(record.serviceId); const requestedPath = parsed.path === "/" ? "/index.html" : parsed.path.endsWith("/") ? `${parsed.path}index.html` : parsed.path; let content; try { content = await targetFs.readPublished(requestedPath); } catch (error) { const manifest = await targetFs.manifest(); const files = manifest?.files ? Array.isArray(manifest.files) ? manifest.files.map((item) => item.path) : Object.keys(manifest.files) : []; const prefix = parsed.path.endsWith("/") ? parsed.path : `${parsed.path}/`; const children = files.filter((path) => path.startsWith(prefix)).map((path) => path.slice(prefix.length).split("/")[0]).filter((value, index, all) => value && all.indexOf(value) === index); if (!children.length) throw error; return { canonicalUrl, scheme, mode: "srcdoc", title: parsed.path, srcdoc: `<main class="directory-index"><h1>${escapeHtml(parsed.path)}</h1><ul>${children.map((child) => `<li>${escapeHtml(child)}</li>`).join("")}</ul></main>`, jam: { serviceId: record.serviceId, name: parsed.name, path: parsed.path } }; } return { canonicalUrl, scheme, mode: "srcdoc", title: parsed.path === "/" ? parsed.name || parsed.serviceId : parsed.path.split("/").filter(Boolean).pop(), srcdoc: renderFile(content.bytes, requestedPath, true, record.serviceId), jam: { serviceId: record.serviceId, name: parsed.name, path: requestedPath } };
}
function renderFile(data: Uint8Array, path: string, jamPage: boolean, serviceId?: string): string { const mime = path.endsWith(".html") || path.endsWith(".htm") ? "text/html" : path.endsWith(".css") ? "text/css" : "text/plain"; if (mime === "text/plain") return `<pre class="raw-file">${escapeHtml(new TextDecoder().decode(data))}</pre>`; let html = new TextDecoder().decode(data).replace(/<jam-link\s+[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/jam-link>/gi, (_all, href, text) => `<a data-jam-link="${escapeAttr(href)}" href="${escapeAttr(href)}">${text}</a>`); html = sanitizeHtml(html); const bridge = jamPage ? `<script>(function(){document.addEventListener('click',function(e){var a=e.target.closest('[data-jam-link]');if(a){e.preventDefault();parent.postMessage({type:'jam:navigate',href:a.getAttribute('data-jam-link')},'*')}})})()</script>` : ""; const base = `<base href="${escapeAttr(path.endsWith("/") ? path : `${path.slice(0, path.lastIndexOf("/") + 1)}`)}">`; void serviceId; return `${base}${html}${bridge}`; }
function sanitizeHtml(html: string) { const candidate = DOMPurify as unknown as { sanitize?: (value: string, options: Record<string, unknown>) => string }; if (typeof candidate.sanitize === "function") return candidate.sanitize(html, { ADD_ATTR: ["data-jam-link"], FORBID_TAGS: ["script", "iframe", "object", "embed"], FORBID_ATTR: ["srcset"] }); return html.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<iframe[\s\S]*?<\/iframe>/gi, "").replace(/<\/?(?:object|embed)(?:\s[^>]*)?>/gi, "").replace(/\son[a-z]+\s*=\s*("[^"]*"|'[^']*')/gi, ""); }
function escapeHtml(input: string) { return input.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!)); }
function escapeAttr(input: string) { return escapeHtml(input).replace(/javascript:/gi, ""); }
