import { useEffect, useRef, useState } from "react";
import { Trophy, Play, RotateCcw, StopCircle, Keyboard, ShieldAlert } from "lucide-react";
import type { Runtime } from "../../runtime";
import type { DoomLeaderboardEntry, DoomResult, DoomSession } from "../../runtime/types";

type View = "home" | "leaderboard" | "running" | "result";
function shortAccount(account: string) { return account.length > 14 ? `${account.slice(0, 7)}…${account.slice(-5)}` : account; }

export function Doom({ runtime, openPlayground: _openPlayground }: { runtime: Runtime; openPlayground: () => void }) {
  const [view, setView] = useState<View>("home"); const [status, setStatus] = useState<"unavailable" | "ready" | "running">("ready"); const [session, setSession] = useState<DoomSession | null>(null); const [result, setResult] = useState<DoomResult | null>(null); const [scores, setScores] = useState<DoomLeaderboardEntry[]>([]); const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => { void runtime.doom.status().then(setStatus); }, [runtime]);
  useEffect(() => { if (view !== "running" || !canvasRef.current) return; const canvas = canvasRef.current; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.fillStyle = "#07090d"; ctx.fillRect(0, 0, canvas.width, canvas.height); const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height); gradient.addColorStop(0, "#342027"); gradient.addColorStop(1, "#0d1416"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#8b3e3e"; ctx.beginPath(); ctx.moveTo(0, 270); ctx.lineTo(90, 198); ctx.lineTo(160, 250); ctx.lineTo(260, 172); ctx.lineTo(360, 244); ctx.lineTo(470, 186); ctx.lineTo(640, 272); ctx.lineTo(640, 360); ctx.lineTo(0, 360); ctx.fill(); ctx.fillStyle = "#e2c4a3"; ctx.font = "700 22px monospace"; ctx.textAlign = "center"; ctx.fillText("DOOM RUNTIME PREVIEW", canvas.width / 2, 70); ctx.fillStyle = "#a4b3c2"; ctx.font = "14px monospace"; ctx.fillText("Canvas framebuffer reserved for MiniJAM PVM frames", canvas.width / 2, 100); }, [view]);
  const start = async () => { const next = await runtime.doom.start({ map: "E1M1", difficulty: "Hurt Me Plenty" }); setSession(next); setStatus("running"); setView("running"); };
  const stop = async () => { if (!session) return; const next = await runtime.doom.stop(session.id); setResult(next); setSession(null); setStatus("ready"); setView("result"); };
  const loadScores = async (account?: string) => { setScores(await runtime.doom.leaderboard(account ? { account } : undefined)); setView("leaderboard"); };
  const sendInput = (event: React.KeyboardEvent) => { if (session) void runtime.doom.input(session.id, { type: "key", value: event.key, pressed: true }); };
  if (view === "leaderboard") return <div className="doom-app doom-leaderboard"><div className="doom-header"><span className="doom-mark small">DOOM</span><button onClick={() => setView("home")}>Back</button></div><div className="doom-tabs"><button className="active">GLOBAL</button><button onClick={() => void loadScores("5MockJAMComputerAccount")}>MY SCORES</button></div><div className="doom-demo-label"><ShieldAlert size={14} /> Preview leaderboard · demo scores are not canonical execution results</div><div className="score-table"><div className="score-row score-heading"><span>Rank</span><span>Player</span><span>Score</span><span>Map</span></div>{scores.map((entry, index) => <div className="score-row" key={entry.id}><strong>#{index + 1}</strong><span>{entry.displayName || shortAccount(entry.account)}{entry.account === "5MockJAMComputerAccount" && " · You"}</span><b>{entry.score.toLocaleString()}</b><small>{entry.map}</small></div>)}</div></div>;
  if (view === "running") return <div className="doom-app doom-running" tabIndex={0} onKeyDown={sendInput}><div className="doom-header"><span className="doom-mark small">DOOM</span><span className="doom-score">12,400</span></div><canvas ref={canvasRef} width={640} height={360} aria-label="DOOM game framebuffer" /><div className="doom-hud"><span>HEALTH <b>87</b></span><span>AMMO <b>38</b></span><span>MAP <b>{session?.map || "E1M1"}</b></span></div><div className="doom-running-actions"><span><Keyboard size={14} /> Focus this window and use keyboard input</span><button onClick={() => void stop()}><StopCircle size={15} /> End run</button></div></div>;
  if (view === "result" && result) return <div className="doom-app doom-result"><span className="doom-mark">DOOM</span><span className="doom-kicker">RUN COMPLETE · PREVIEW RESULT</span><h2>{result.score.toLocaleString()}</h2><div className="result-grid"><span>Map<b>{result.map}</b></span><span>Kills<b>{result.kills}</b></span><span>Duration<b>{Math.round(result.durationMs / 1000)}s</b></span></div><p>This result is produced by the mock adapter and is not a trusted MiniJAM receipt.</p><div className="doom-actions"><button className="doom-primary" onClick={() => void start()}><RotateCcw size={16} /> Play again</button><button onClick={() => void loadScores()}><Trophy size={16} /> View leaderboard</button></div></div>;
  return <div className="doom-app doom-home"><span className="doom-mark">DOOM</span><span className="doom-kicker">JAM COMPUTER GAME ROOM</span><h2>{status === "ready" ? "DOOM Runtime Preview" : "PVM runtime not connected"}</h2><p>Canvas framebuffer and trusted-result boundaries are ready for a future MiniJAM execution adapter.</p><button className="doom-primary" disabled={status !== "ready"} onClick={() => void start()}><Play size={17} /> START GAME</button><button className="doom-link" onClick={() => void loadScores()}><Trophy size={15} /> GLOBAL LEADERBOARD</button><small className="coming-soon">Demo scores · runtime: {runtime.mode}</small></div>;
}
