import { useEffect, useState } from "react";
import { Trophy, Play, RotateCcw, StopCircle, ShieldAlert } from "lucide-react";
import type { JamOsRuntimeV2 } from "../../runtime/types";
import type { DoomLeaderboardEntry, DoomResult, DoomRuntimeStatus, DoomSession } from "../../runtime/types";

type View = "home" | "leaderboard" | "running" | "result";
function shortAccount(account: string) { return account.length > 14 ? `${account.slice(0, 7)}…${account.slice(-5)}` : account; }

export function Doom({ runtime, openPlayground: _openPlayground }: { runtime: JamOsRuntimeV2; openPlayground: () => void }) {
  const [view, setView] = useState<View>("home");
  const [status, setStatus] = useState<DoomRuntimeStatus>("unavailable");
  const [session, setSession] = useState<DoomSession | null>(null);
  const [result, setResult] = useState<DoomResult | null>(null);
  const [scores, setScores] = useState<DoomLeaderboardEntry[]>([]);
  const [account, setAccount] = useState<string | null>(null);
  const [tick, setTick] = useState(0);
  const [error, setError] = useState("");
  const [failed, setFailed] = useState(false);
  useEffect(() => { void runtime.doom.status().then(setStatus); void runtime.account.current().then((current) => setAccount(current?.address || null)); }, [runtime]);
  const start = async () => { try { setError(""); setFailed(false); const next = await runtime.doom.createSession({ map: "E1M1", difficulty: "Hurt Me Plenty" }); setSession(next); setTick(0); setStatus("running"); setView("running"); } catch (cause) { setFailed(true); setError(cause instanceof Error ? cause.message : "DOOM runtime unavailable"); } };
  const advance = async () => { if (!session) return; try { setError(""); setFailed(false); const next = await runtime.doom.executeTicks(session.id, 60); setTick(next.toTick); } catch (cause) { setFailed(true); setError(cause instanceof Error ? cause.message : "Unable to execute DOOM ticks"); } };
  const stop = async () => { if (!session) return; try { const next = await runtime.doom.finish(session.id); setResult(next); setSession(null); setStatus("ready"); setView("result"); } catch (cause) { setFailed(true); setError(cause instanceof Error ? cause.message : "Unable to finish DOOM session"); } };
  const loadScores = async (mine = false) => { if (!runtime.doom.leaderboard) return; const currentAccount = mine ? account || (await runtime.account.current())?.address : undefined; setScores(await runtime.doom.leaderboard(currentAccount ? { account: currentAccount } : undefined)); setView("leaderboard"); };
  if (view === "leaderboard") return <div className="doom-app doom-leaderboard"><div className="doom-header"><span className="doom-mark small">DOOM</span><button onClick={() => setView("home")}>Back</button></div><div className="doom-tabs"><button className="active">GLOBAL</button><button onClick={() => void loadScores(true)}>MY SCORES</button></div><div className="doom-demo-label"><ShieldAlert size={14} /> Phase 3A preview scores · no leaderboard service is connected</div><div className="score-table"><div className="score-row score-heading"><span>Rank</span><span>Player</span><span>Score</span><span>Map</span></div>{scores.map((entry, index) => <div className="score-row" key={entry.id}><strong>#{index + 1}</strong><span>{entry.displayName || shortAccount(entry.account)}{account && entry.account === account && " · You"}</span><b>{entry.score.toLocaleString()}</b><small>{entry.map}</small></div>)}</div></div>;
  if (view === "running") return <div className="doom-app doom-running"><div className="doom-header"><span className="doom-mark small">DOOM</span><span className="doom-score">{tick.toLocaleString()} ticks</span></div><div className="doom-preview-frame"><strong>DETERMINISTIC DOOM RUNTIME</strong><span>Canvas execution is reserved for Phase 3C</span></div><div className="doom-hud"><span>HEALTH <b>—</b></span><span>AMMO <b>—</b></span><span>MAP <b>{session?.map || "E1M1"}</b></span></div><div className="doom-running-actions"><span>{session?.runtimeVersion} · ruleset {session?.rulesetVersion}</span><button onClick={() => void advance()}>Advance 60 ticks</button><button onClick={() => void stop()}><StopCircle size={15} /> End run</button></div>{error && <p className="error-text">{error}</p>}</div>;
  if (view === "result" && result) return <div className="doom-app doom-result"><span className="doom-mark">DOOM</span><span className="doom-kicker">RUN COMPLETE · DETERMINISTIC RESULT</span><h2>{result.score.toLocaleString()}</h2><div className="result-grid"><span>Map<b>{result.map}</b></span><span>Kills<b>{result.kills}</b></span><span>Ticks<b>{result.durationTicks}</b></span></div><p>Runtime {result.runtimeVersion} · ruleset {result.rulesetVersion}</p><small className="mono">State {result.finalStateHash}</small>{import.meta.env.DEV && result.execution && <small className="mono">Work {result.execution.workId} · Receipt {result.execution.receiptHash || "pending"}</small>}<div className="doom-actions"><button className="doom-primary" onClick={() => void start()}><RotateCcw size={16} /> Play again</button><button onClick={() => void loadScores()}><Trophy size={16} /> View preview scores</button></div></div>;
  const label = failed ? "Failed" : status === "ready" ? "Available" : status === "running" ? "Running" : "Unavailable";
  return <div className="doom-app doom-home"><span className="doom-mark">DOOM</span><span className="doom-kicker">JAM COMPUTER GAME ROOM</span><h2>DOOM · {label}</h2><p>Deterministic DOOM execution through the configured runtime.</p><button className="doom-primary" disabled={status !== "ready"} onClick={() => void start()}><Play size={17} /> START GAME</button><button className="doom-link" disabled={!runtime.doom.leaderboard} onClick={() => void loadScores()}><Trophy size={16} /> PREVIEW SCORES</button>{error && <p className="error-text">{error}</p>}<small className="coming-soon">Runtime status: {label}</small></div>;
}
