import { normalizePath } from "../../protocols/jamFs";
import type { AccountAdapter, AccountInfo } from "../../jam/types";
import { JamScriptComputerBackend } from "../../jam/computerBackend";
import { contentRefFromJson, type ContentProvider } from "../../jam/contentProvider";
import type { FileEntry, FileManifest, FileSystemRuntime, WorkRuntime } from "../types";
import { MiniJamApiError, MiniJamApiClient } from "./MiniJamApiClient";

type NodeValue = { path?: unknown; kind?: unknown; parent?: unknown; mime?: unknown; size?: unknown; contentRoot?: unknown; removed?: unknown; updatedAt?: unknown };
const ROOT = new Uint8Array([0]);
const text = (value: unknown) => value instanceof Uint8Array ? new TextDecoder().decode(value).replaceAll("\0", "").trim() : "";
const bytes = (value: string) => new TextEncoder().encode(value);
const uint = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : 0;
const root = (value: unknown) => value instanceof Uint8Array && value.length === 32 ? `0x${Array.from(value, (byte) => byte.toString(16).padStart(2, "0")).join("")}` : "0x";
function decodeIndex(value: unknown): string[] { if (!value || typeof value !== "object" || value instanceof Uint8Array || Array.isArray(value)) return []; const entries = (value as { entries?: unknown }).entries; return entries instanceof Uint8Array ? new TextDecoder().decode(entries).split("\n").map((entry) => entry.trim()).filter(Boolean) : []; }
function encodeIndex(entries: string[]): Uint8Array { const encoded = bytes([...new Set(entries.map((entry) => entry.trim()).filter(Boolean))].sort().join("\n")); if (encoded.length > 4096) throw new MiniJamApiError("DIRECTORY_TOO_LARGE", "Directory index exceeds the Stage-1 bound"); return encoded; }

export class LiveFileSystemRuntime implements FileSystemRuntime {
  private readonly backend?: JamScriptComputerBackend;
  constructor(private readonly api: MiniJamApiClient, private readonly work: WorkRuntime, private readonly account?: AccountAdapter, private readonly serviceId?: string, private readonly content?: ContentProvider) { if (serviceId && account && (import.meta.env.VITE_MINIJAM_RPC_URL || import.meta.env.VITE_MINIJAM_NODE_RPC_URL)) this.backend = new JamScriptComputerBackend(serviceId, account); }
  private get id() { if (!this.serviceId) throw new MiniJamApiError("SERVICE_UNAVAILABLE", "Computer Service is not mounted"); return this.serviceId; }
  private async owner(): Promise<AccountInfo> { const account = await this.account?.current(); if (!account) throw new MiniJamApiError("UNAUTHORIZED", "Connect an account before changing JAM files", 401); return account; }
  private async query(name: string, key: string): Promise<unknown | null> { if (!this.backend) throw new MiniJamApiError("NETWORK_UNAVAILABLE", "MiniJAM RPC URL is not configured", undefined, true); return this.backend.query(name, bytes(key)); }
  private nodeFrom(path: string, value: unknown): FileEntry | null { if (!value || typeof value !== "object" || value instanceof Uint8Array || Array.isArray(value)) return null; const node = value as NodeValue; if (node.removed === true) return null; return { path: text(node.path) || path, type: text(node.kind) === "directory" ? "directory" : "file", size: uint(node.size), mime: text(node.mime) || undefined, updatedAt: uint(node.updatedAt) || undefined }; }
  async stat(path: string) { const normalized = normalizePath(path); return this.nodeFrom(normalized, await this.query("getNodeMetadata", normalized)); }
  async list(path: string) { const normalized = normalizePath(path); const entries = decodeIndex(await this.query("getDirectoryIndex", normalized)); const values = await Promise.all(entries.map(async (name) => this.stat(`${normalized === "/" ? "" : normalized}/${name}`))); return values.filter((entry): entry is FileEntry => Boolean(entry)); }
  async read(path: string) { const normalized = normalizePath(path); const value = await this.query("getNodeMetadata", normalized); const node = value && typeof value === "object" && !(value instanceof Uint8Array) ? value as NodeValue : null; if (!node || node.removed === true || text(node.kind) === "directory") throw new MiniJamApiError("NOT_FOUND", normalized, 404); if (!this.content) throw new MiniJamApiError("CONTENT_UNAVAILABLE", "ContentProvider is not configured", undefined, true); return this.content.get(contentRefFromJson({ version: 1, root: root(node.contentRoot), size: uint(node.size) })); }
  readText(path: string) { return this.read(path).then((value) => new TextDecoder().decode(value)); }
  async write(path: string, data: Uint8Array, options?: { mime?: string }) { const normalized = normalizePath(path); const parent = normalized.slice(0, normalized.lastIndexOf("/")) || "/"; if (!this.content || !this.backend) throw new MiniJamApiError("CONTENT_UNAVAILABLE", "ContentProvider is not configured"); const owner = await this.owner(); const parentNode = await this.stat(parent); if (!parentNode || parentNode.type !== "directory") throw new MiniJamApiError("NOT_FOUND", parent, 404); const ref = await this.content.put(data); await this.backend.action("setNodeMetadata", { key: ROOT, path: bytes(normalized), kind: bytes("file"), parent: bytes(parent), mime: bytes(options?.mime || "application/octet-stream"), size: data.length, contentRoot: new Uint8Array(ref.root.slice(2).match(/../g)!.map((part) => parseInt(part, 16))), updatedAt: Math.floor(Date.now() / 1000) }, owner); await this.updateIndex(parent, normalized.split("/").pop() || "", owner); }
  writeText(path: string, content: string, mime?: string) { return this.write(path, new TextEncoder().encode(content), { mime }); }
  async mkdir(path: string) { const normalized = normalizePath(path); const parent = normalized.slice(0, normalized.lastIndexOf("/")) || "/"; const name = normalized.split("/").pop() || "/"; if (!this.backend) throw new MiniJamApiError("SERVICE_UNAVAILABLE", "Computer Service is not mounted"); const owner = await this.owner(); const parentNode = await this.stat(parent); if (!parentNode || parentNode.type !== "directory") throw new MiniJamApiError("NOT_FOUND", parent, 404); if (await this.stat(normalized)) throw new MiniJamApiError("ALREADY_EXISTS", normalized, 409); await this.backend.action("setNodeMetadata", { key: ROOT, path: bytes(normalized), kind: bytes("directory"), parent: bytes(parent), mime: bytes("inode/directory"), size: 0, contentRoot: new Uint8Array(32), updatedAt: Math.floor(Date.now() / 1000) }, owner); await this.updateIndex(parent, name, owner); }
  async remove(path: string, options: { recursive?: boolean } = {}) { const normalized = normalizePath(path); if (!this.backend) throw new MiniJamApiError("SERVICE_UNAVAILABLE", "Computer Service is not mounted"); const owner = await this.owner(); const node = await this.query("getNodeMetadata", normalized); if (!node) throw new MiniJamApiError("NOT_FOUND", normalized, 404); if (text((node as NodeValue).kind) === "directory" && !options.recursive && (await this.list(normalized)).length) throw new MiniJamApiError("DIRECTORY_NOT_EMPTY", normalized, 409); await this.backend.action("removeNodeMetadata", { key: ROOT, path: bytes(normalized), updatedAt: Math.floor(Date.now() / 1000) }, owner); await this.updateIndex(normalized.slice(0, normalized.lastIndexOf("/")) || "/", normalized.split("/").pop() || "", owner, true); }
  async rename(from: string, to: string) { const source = normalizePath(from); const target = normalizePath(to); if (!this.backend) throw new MiniJamApiError("SERVICE_UNAVAILABLE", "Computer Service is not mounted"); const owner = await this.owner(); const node = await this.query("getNodeMetadata", source); if (!node) throw new MiniJamApiError("NOT_FOUND", source, 404); const sourceNode = node as NodeValue; if (text(sourceNode.kind) === "directory") throw new MiniJamApiError("DIRECTORY_RENAME_UNSUPPORTED", "Stage-1 only supports file rename"); const parent = target.slice(0, target.lastIndexOf("/")) || "/"; if (!(await this.stat(parent))) throw new MiniJamApiError("NOT_FOUND", parent, 404); const rawRoot = sourceNode.contentRoot; const contentRoot: Uint8Array = rawRoot instanceof Uint8Array ? rawRoot : new Uint8Array(32); await this.backend.action("setNodeMetadata", { key: ROOT, path: bytes(target), kind: bytes("file"), parent: bytes(parent), mime: bytes(text(sourceNode.mime) || "application/octet-stream"), size: uint(sourceNode.size), contentRoot, updatedAt: Math.floor(Date.now() / 1000) }, owner); await this.backend.action("removeNodeMetadata", { key: ROOT, path: bytes(source), updatedAt: Math.floor(Date.now() / 1000) }, owner); await this.updateIndex(source.slice(0, source.lastIndexOf("/")) || "/", source.split("/").pop() || "", owner, true); await this.updateIndex(parent, target.split("/").pop() || "", owner); }
  private async updateIndex(path: string, child: string, owner: AccountInfo, remove = false) { if (!this.backend || !child) return; const current = decodeIndex(await this.query("getDirectoryIndex", path)); const next = remove ? current.filter((entry) => entry !== child) : [...current, child]; await this.backend.action("setDirectoryIndex", { key: ROOT, path: bytes(path), entries: encodeIndex(next) }, owner); }
  async publish(path = "/home/user/Sites/home"): Promise<FileManifest> {
    if (!this.backend) throw new MiniJamApiError("NETWORK_UNAVAILABLE", "MiniJAM RPC URL is not configured", undefined, true);
    const owner = await this.owner(); const normalized = normalizePath(path); const files: Array<{ path: string; mime: string; size: number; contentRoot: string }> = [];
    const walk = async (directory: string, prefix: string): Promise<void> => { for (const entry of await this.list(directory)) { if (entry.type === "directory") await walk(entry.path, `${prefix}${entry.path.slice(directory.length).replace(/^\//, "")}/`); else { const node = await this.query("getNodeMetadata", entry.path) as NodeValue | null; const contentRoot = root(node?.contentRoot); if (contentRoot === "0x") throw new MiniJamApiError("INVALID_CONTENT_REF", entry.path); files.push({ path: `${prefix}${entry.path.slice(directory.length).replace(/^\//, "")}`, mime: entry.mime || "application/octet-stream", size: entry.size, contentRoot }); } } };
    await walk(normalized, "/"); files.sort((left, right) => left.path.localeCompare(right.path)); if (!files.some((file) => file.path === "/index.html")) throw new MiniJamApiError("SITE_INDEX_NOT_FOUND", "Published site requires /index.html", 400);
    const entries = bytes(files.map((file) => `${file.path}|${file.mime}|${file.size}|${file.contentRoot}`).join("\n")); if (entries.length > 4096) throw new MiniJamApiError("SITE_TOO_LARGE", "Site manifest exceeds the Stage-1 bound");
    await this.backend.action("publishSite", { key: ROOT, index: bytes("/index.html"), entries, publishedAt: Math.floor(Date.now() / 1000) }, owner); return { version: 1, indexPath: "/index.html", files };
  }
  async manifest(): Promise<FileManifest | null> { const value = await this.query("getSiteManifest", "\0"); if (!value || typeof value !== "object" || value instanceof Uint8Array || Array.isArray(value) || (value as { published?: unknown }).published !== true) return null; const manifest = value as { index?: unknown; entries?: unknown }; const lines = manifest.entries instanceof Uint8Array ? new TextDecoder().decode(manifest.entries).split("\n").filter(Boolean) : []; const files = lines.map((line) => { const [path, mime, size, contentRoot] = line.split("|"); return { path, mime, size: Number(size), contentRoot }; }); return { version: 1, indexPath: text(manifest.index) || "/index.html", files }; }
  async readPublished(path: string): Promise<{ bytes: Uint8Array; mime: string }> { const manifest = await this.manifest(); if (!manifest) throw new MiniJamApiError("NOT_FOUND", "No published site", 404); const entry = Array.isArray(manifest.files) ? manifest.files.find((item) => item.path === normalizePath(path)) : undefined; if (!entry || !entry.contentRoot || !this.content) throw new MiniJamApiError("NOT_FOUND", path, 404); return { bytes: await this.content.get(contentRefFromJson({ version: 1, root: entry.contentRoot, size: entry.size || 0 })), mime: entry.mime || "application/octet-stream" }; }
  mount(serviceId: string) { return new LiveFileSystemRuntime(this.api, this.work, this.account, serviceId, this.content); }
}
