import type { AccountAdapter, AccountInfo } from "../../jam/types";
import { base64ToBytes } from "../../jam/encoding";
import type { EventRuntime, WorkHandle, WorkRequest, WorkResult, WorkRuntime, WorkStatus, WorkWaitOptions } from "../types";
import { MiniJamApiClient, MiniJamApiError } from "./MiniJamApiClient";

type OperationLike = Awaited<ReturnType<MiniJamApiClient["getOperation"]>>;

function statusOf(operation: OperationLike): WorkStatus { const terminal = operation.status === "succeeded" ? "complete" : operation.status === "failed" ? "failed" : ["prepared", "submitted"].includes(operation.status) ? "queued" : "running"; return { id: operation.operationId, state: terminal, detail: operation.status }; }

export class LiveWorkRuntime implements WorkRuntime {
  constructor(private readonly api: MiniJamApiClient, private readonly account: AccountAdapter, private readonly events: EventRuntime) {}
  async submit(input: WorkRequest): Promise<WorkHandle> { const current: AccountInfo | null = await this.account.current(); if (!current) throw new MiniJamApiError("UNAUTHORIZED", "Connect a Polkadot account before submitting Work", 401); const operation = await this.api.submitWork({ serviceId: input.serviceId, payload: input.payload, extrinsics: input.extrinsics, account: current, signer: this.account }); this.events.emit?.("work:submitted", { id: operation.operationId, operationId: operation.operationId, serviceId: input.serviceId }); return { id: operation.operationId, submittedAt: Date.now() }; }
  async status(workId: string): Promise<WorkStatus> { const operation = await this.api.getOperation(workId); return statusOf(operation); }
  async wait(workId: string, options: WorkWaitOptions = {}): Promise<WorkResult> { const timeoutMs = options.timeoutMs ?? 120_000; const started = Date.now(); let delay = 500; while (true) { if (options.signal?.aborted) throw new MiniJamApiError("WORK_ABORTED", "Stopped waiting for Work; the MiniJAM operation was not cancelled", undefined, false); if (Date.now() - started >= timeoutMs) throw new MiniJamApiError("WORK_TIMEOUT", `Work ${workId} did not complete before the timeout`, undefined, true); const operation = await this.api.getOperation(workId); const status = statusOf(operation); if (status.state === "failed") { this.events.emit?.("work:failed", { id: workId, operation }); throw new MiniJamApiError("WORK_FAILED", operation.error || `Work ${workId} failed`, undefined, false); } if (status.state === "complete") { const output = operation.result?.outputBase64 ? base64ToBytes(operation.result.outputBase64) : new Uint8Array(); const result = { id: workId, output, completedAt: Date.now(), operationId: workId, workId: operation.result?.workId == null ? undefined : String(operation.result.workId), serviceId: operation.request?.serviceId == null ? undefined : String(operation.request.serviceId), receiptHash: operation.result?.executionReceipt }; this.events.emit?.("work:completed", result); return result; } this.events.emit?.("work:running", { id: workId, status: operation.status }); await new Promise<void>((resolve, reject) => { const timer = globalThis.setTimeout(resolve, delay); const abort = () => { globalThis.clearTimeout(timer); reject(new MiniJamApiError("WORK_ABORTED", "Stopped waiting for Work; the MiniJAM operation was not cancelled", undefined, false)); }; options.signal?.addEventListener("abort", abort, { once: true }); }); delay = 1000; } }
}
