import { useEffect, useMemo, useRef, useState } from "react";
import { Network, Search, Wifi, Power, RotateCcw } from "lucide-react";
import { BootScreen } from "./boot/BootScreen";
import { DesktopIcon } from "./desktop/DesktopIcon";
import { Taskbar } from "./desktop/Taskbar";
import { Window } from "./desktop/Window";
import type { WindowInstance } from "./desktop/types";
import { createRuntime } from "./runtime";
import type { JamOsRuntimeV2 } from "./runtime/types";
import type { ProvisionProgress } from "./jam/computer";
import type { AccountInfo } from "./jam/types";
import { getAppManifest, systemApps } from "./os/appRegistry";
import "./styles/global.css";
import "./styles/boot-polish.css";
import "./styles/os.css";
import { PublicComputerPage } from "./public/PublicComputerPage";

type Phase = "boot" | "login" | "connecting" | "account" | "provisioning" | "desktop" | "error";

export default function App() {
  const preview = import.meta.env.VITE_JAM_MODE !== "live" && (new URLSearchParams(window.location.search).get("preview") === "1" || window.location.hash === "#preview");
  const runtime = useMemo(() => createRuntime(preview), [preview]);
  const publicName = window.location.pathname.match(/^\/@([a-z0-9-]+)$/i)?.[1]?.toLowerCase();
  const [phase, setPhase] = useState<Phase>("boot"); const [account, setAccount] = useState<AccountInfo | null>(null); const [serviceId, setServiceId] = useState<string | null>(null); const [progress, setProgress] = useState<ProvisionProgress[]>([]); const [error, setError] = useState(""); const [windows, setWindows] = useState<WindowInstance[]>([]); const [showStart, setShowStart] = useState(false); const [selected, setSelected] = useState<string | null>(null); const [networkName, setNetworkName] = useState("MiniJAM"); const zIndex = useRef(20);
  useEffect(() => { if (phase !== "boot") return; const timer = window.setTimeout(() => setPhase("login"), 1200); return () => window.clearTimeout(timer); }, [phase]);
  useEffect(() => { void runtime.network.getInfo().then((info) => setNetworkName(info.name)).catch(() => undefined); }, [runtime]);
  if (publicName) return <PublicComputerPage name={publicName} runtime={runtime} />;
  const connectAccount = async () => { setPhase("connecting"); setError(""); try { const connected = await runtime.account.connect(); setAccount(connected); setPhase("account"); runtime.events.emit?.("account:connected", connected); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to connect account"); setPhase("login"); } };
  const openApp = (appId: string, args?: string) => { const manifest = getAppManifest(appId); setWindows((old) => { const existing = manifest.singleton ? old.find((item) => item.appId === appId) : undefined; if (existing) return old.map((item) => item.id === existing.id ? { ...item, minimized: false, args, zIndex: ++zIndex.current } : item); const offset = old.length * 26; return [...old, { id: `${appId}-${Date.now()}`, appId, title: manifest.name, x: 105 + offset, y: 58 + offset, width: manifest.defaultWidth, height: manifest.defaultHeight, zIndex: ++zIndex.current, minimized: false, maximized: false, args }]; }); setSelected(appId); setShowStart(false); };
  const provision = async () => { setPhase("provisioning"); setProgress([]); setError(""); try { const result = await runtime.computer.provision((item) => setProgress((old) => [...old.filter((entry) => entry.step !== item.step), item])); setAccount(result.account); setServiceId(result.serviceId); setPhase("desktop"); runtime.events.emit?.("service:started", result.serviceId); openApp("computer"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to start JAM Computer"); setPhase("error"); } };
  const updateWindow = (id: string, fn: (item: WindowInstance) => WindowInstance) => setWindows((old) => old.map((item) => item.id === id ? fn(item) : item));
  const focus = (id: string) => { const next = ++zIndex.current; updateWindow(id, (item) => ({ ...item, zIndex: next, minimized: false })); };
  const appContent = (item: WindowInstance) => { const Component = getAppManifest(item.appId).component; return <Component runtime={runtime} serviceId={serviceId} openApp={openApp} />; };
  if (phase !== "desktop") return <BootScreen phase={phase} mode={runtime.mode} networkName={networkName} account={account} progress={progress} error={error} onSignIn={() => void connectAccount()} onContinue={() => void provision()} onRetry={() => void provision()} />;
  const desktopApps = systemApps.filter((app) => app.id !== "services");
  return <main className="desktop-shell" onClick={() => showStart && setShowStart(false)}><div className="desktop-background"><header className="os-topbar"><div className="os-brand"><span className="os-brand-mark">◆</span><strong>JAM OS</strong><small>0.1</small></div><div className="topbar-center">MiniJAM <span className="status-dot" /> {runtime.mode === "mock" ? "Preview" : "Connected"}</div><div className="topbar-status"><Network size={14} /><span>{networkName}</span><Wifi size={14} /><span>{new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div></header><aside className="desktop-icons" aria-label="Desktop applications">{desktopApps.map((app) => <DesktopIcon key={app.id} icon={app.icon} title={app.name} selected={selected === app.id} onSelect={() => setSelected(app.id)} onOpen={() => openApp(app.id)} />)}</aside><section className="desktop-caption"><span>JAM COMPUTER</span><small>{runtime.mode === "mock" ? "Preview runtime · local demo data" : "MiniJAM-backed computer"}</small></section><aside className="system-widgets"><SystemWidget runtime={runtime} serviceId={serviceId} networkName={networkName} /><ServiceWidget runtime={runtime} /><LogWidget runtime={runtime} /></aside>{windows.map((item) => <Window key={item.id} window={item} onFocus={() => focus(item.id)} onMove={(x, y) => updateWindow(item.id, (current) => ({ ...current, x, y }))} onResize={(width, height) => updateWindow(item.id, (current) => ({ ...current, width, height }))} onMinimize={() => updateWindow(item.id, (current) => ({ ...current, minimized: true }))} onMaximize={() => updateWindow(item.id, (current) => ({ ...current, maximized: !current.maximized }))} onClose={() => setWindows((old) => old.filter((current) => current.id !== item.id))}>{appContent(item)}</Window>)}</div><Taskbar windows={windows} mode={runtime.mode} network={networkName} onOpen={() => setShowStart((value) => !value)} onFocus={focus} />{showStart && <StartMenu runtime={runtime} openApp={openApp} />}</main>;
}

function SystemWidget({ runtime, serviceId, networkName }: { runtime: JamOsRuntimeV2; serviceId: string | null; networkName: string }) { const [info, setInfo] = useState<Awaited<ReturnType<JamOsRuntimeV2["system"]["getInfo"]>> | null>(null); useEffect(() => { void runtime.system.getInfo().then(setInfo); }, [runtime, serviceId]); const metric = (value: number | undefined, source: string | undefined, suffix = "") => <span>{value === undefined ? "—" : `${value}${suffix}`} <i className={`metric-source ${source || "unavailable"}`} title={`Data source: ${source || "unavailable"}`} /></span>; return <article className="widget-card"><div className="widget-heading"><span>SYSTEM</span><small>{info?.status || "booting"}</small></div><div className="widget-row"><span>CPU</span>{metric(info?.cpuUsage?.value, info?.cpuUsage?.source, "%")}</div><div className="widget-row"><span>Memory</span>{metric(info?.memoryUsage?.value, info?.memoryUsage?.source, " GB")}<em>/ {info?.memoryTotal?.value || 4} GB</em></div><div className="widget-row"><span>Storage</span>{metric(info?.storageUsed?.value, info?.storageUsed?.source, " MB")}<em>/ {info?.storageTotal?.value || 64} GB</em></div><div className="widget-footer"><span><span className="status-dot" /> {networkName}</span><span>{serviceId ? `Service #${serviceId}` : "Service starting"}</span></div></article>; }
function ServiceWidget({ runtime }: { runtime: JamOsRuntimeV2 }) { const [services, setServices] = useState<Awaited<ReturnType<JamOsRuntimeV2["services"]["list"]>>>([]); useEffect(() => { void runtime.services.list().then(setServices); }, [runtime]); return <article className="widget-card"><div className="widget-heading"><span>JAM SERVICES</span><small>{services.length} running</small></div>{services.map((service) => <div className="service-line" key={service.id}><span className="status-dot" /><span>{service.name}</span><small>{service.source}</small></div>)}</article>; }
function LogWidget({ runtime }: { runtime: JamOsRuntimeV2 }) { const [logs, setLogs] = useState(runtime.mode === "mock" ? ["JAM OS started", "MiniJAM connected", "Computer Service ready"] : ["Waiting for live runtime events"]); useEffect(() => { const messages: Record<string, string> = { "account:connected": "Account connected", "network:online": "MiniJAM connected", "network:offline": "MiniJAM unavailable", "service:started": "Computer Service ready", "work:submitted": "Work submitted", "work:running": "Work running", "work:completed": "Work completed", "work:failed": "Work failed" }; const cleanups = Object.entries(messages).map(([event, message]) => runtime.events.subscribe(event, () => setLogs((old) => [...old.slice(-2), message]))); return () => cleanups.forEach((cleanup) => cleanup()); }, [runtime]); return <article className="widget-card log-widget"><div className="widget-heading"><span>LOGS</span><small>system events</small></div>{logs.map((log, index) => <div className="log-line" key={`${log}-${index}`}><span>[00:{35 + index}:4{index}]</span> {log}</div>)}</article>; }
function StartMenu({ runtime, openApp }: { runtime: JamOsRuntimeV2; openApp: (id: string) => void }) { const [query, setQuery] = useState(""); const apps = systemApps.filter((app) => app.id !== "trash" && app.name.toLowerCase().includes(query.toLowerCase())); return <div className="start-menu" onClick={(event) => event.stopPropagation()}><div className="start-heading"><span className="os-brand-mark">◆</span><div><strong>JAM Computer</strong><small>{runtime.mode.toUpperCase()} runtime</small></div></div><label className="start-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search apps" autoFocus /></label><div className="start-label">Pinned</div>{apps.map((app) => { const Icon = app.icon; return <button key={app.id} onClick={() => openApp(app.id)}><Icon size={17} /><span>{app.name}</span></button>; })}<div className="start-footer"><button><Power size={15} /> Shutdown</button><button><RotateCcw size={15} /> Restart</button></div></div>; }
