import { useEffect, useState } from "react";
import { Cpu, HardDrive, Network, Server, UserRound } from "lucide-react";
import type { JamOsRuntimeV2 } from "../../runtime/types";

export function MyComputer({ runtime, serviceId, openEditor: _openEditor }: { runtime: JamOsRuntimeV2; serviceId: string | null; openEditor: (path: string) => void }) {
  const [info, setInfo] = useState<Awaited<ReturnType<JamOsRuntimeV2["system"]["getInfo"]>> | null>(null); const [account, setAccount] = useState<{ address: string } | null>(null); const [services, setServices] = useState<Awaited<ReturnType<JamOsRuntimeV2["services"]["list"]>>>([]);
  useEffect(() => { void runtime.system.getInfo().then(setInfo); void runtime.account.current().then(setAccount); void runtime.services.list().then(setServices); }, [runtime, serviceId]);
  return <div className="computer-app"><div className="computer-hero"><div className="computer-icon"><Server size={34} /></div><div><small>JAM OS SYSTEM</small><h2>JAM Computer</h2><p>{info?.status === "online" ? "Your computer is ready." : "Checking computer status…"}</p></div></div><div className="computer-grid"><div className="info-tile"><UserRound size={16} /><small>Account</small><b>{account?.address ? `${account.address.slice(0, 8)}…` : "Not connected"}</b></div><div className="info-tile"><Network size={16} /><small>Network</small><b>{info?.networkName || "MiniJAM"}</b></div><div className="info-tile"><HardDrive size={16} /><small>Storage</small><b>{info?.storageUsed?.value || 0} MB / {info?.storageTotal?.value || 64} GB</b></div><div className="info-tile"><Cpu size={16} /><small>Service</small><b>{serviceId ? `#${serviceId}` : "Starting"}</b></div></div><section className="computer-services"><div className="settings-label">INSTALLED SERVICES</div>{services.map((service) => <div className="service-line" key={service.id}><span className="status-dot" /><span>{service.name}</span><small>{service.status}</small></div>)}</section><p className="settings-note">Metrics marked as mock are presentation data until the live MiniJAM client exposes system telemetry.</p></div>;
}
